### ISSUE TITLE
`pip install` cannot work

### ISSUE THREAD

**Issue by KornbergFresnel** [cair/deep-rts#5]
The latest pip (19.0.3) for python3 cannot install deep-rts with your instruction. Could you provide more information about the available version or solutions? thx.

**installation error message**

```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/UIA-CAIR/DeepRTS
  Cloning https://github.com/UIA-CAIR/DeepRTS to /tmp/pip-req-build-8m608ix7
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-8m608ix7/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-8m608ix7/
```

**Comment by perara** [comment]
try the command
sudo pip3 git+https://github.com/cair/DeepRTS

**Comment by KornbergFresnel** [comment]
@perara Thanks for your rapid response. But result of executing `sudo pip3 git+https://github.com/cair/DeepRTS` shows that it is not correct:

```
ERROR: unknown command "git+https://github.com/cair/DeepRTS"
```

I think it should be `sudo pip3 install git+https://github.com/cair/DeepRTS` (reference: [use GitHub as a PyPi server](https://medium.freecodecamp.org/how-to-use-github-as-a-pypi-server-1c3b0d07db2))

But the key to the issue may be the path of `setup.py` is not correct, I mean, `setup.py` should be in root directory. (I've tried `sudo pip3 install git+https://github.com/cair/DeepRTS`, while there was still an error:

```
Collecting git+https://github.com/cair/DeepRTS
  Cloning https://github.com/cair/DeepRTS to /tmp/pip-req-build-mam4_n2v
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-mam4_n2v/setup.py'
```
)

**Comment by perara** [comment]
Hi,

You are correct. i've done some restructuring a while back which broke it. Currently, your best bet is to download the code and install it manually (best is to just run from source). I'll correct this as soon as possible.

**Comment by perara** [comment]
You could also try a older commit: https://github.com/cair/deep-rts/tree/cace3c2c55ef3d86906ad492b0779d832df218c2

**Comment by KornbergFresnel** [comment]
@perara Thanks.
