### ISSUE TITLE
Fatal Python error: (pygame prachute) Segmentation Fault

### ISSUE THREAD

**Issue by KornbergFresnel** [cair/deep-rts#6]
I've tried to run your given example in README, then the script thrown an exception at `g.update()`:

```
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
[FPS=0, UPS=0]
Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0x00007feadc869740 (most recent call first):
  File "test.py", line 25 in <module>
[1]    23004 abort (core dumped)  python3 test.py
```

**System information**

ubuntu 16.0.4
python 3.6
pygame 1.9.4
DeepRTS latest version

**Comment by dhinadhinesh007** [comment]
Were you able to resolve this issue?

**Comment by perara** [comment]
Hi, could you try the lastest version? I am not experiencing this error

**Comment by zdx3578** [comment]
@perara https://arxiv.org/pdf/1907.11971.pdf this paper rl code will open? or have other deep-rts rl code?

**Comment by perara** [comment]
> @perara https://arxiv.org/pdf/1907.11971.pdf this paper rl code will open? or have other deep-rts rl code?

I'm not sure if I understand the question.

**Comment by perara** [comment]
@zdx3578 Perhaps you are looking for https://github.com/cair/deep-warehouse ?

**Comment by zdx3578** [comment]
I am Very interested Tsetlin machine ,I  Want to ask are there any RL code integrate with Tsetlin machine code? like Gym env ; or integrate with deep-rts;

**Comment by perara** [comment]
Hi,

Not that I am aware of TM put into an RL setting. But I'll tag @olegranmo which might be able to guide you further.

**Comment by zdx3578** [comment]
@perara thanks very much!

**Comment by olegranmo** [comment]
Hi @zdx3578! Thanks for your interest in the TM.

We are currently working on RL based on the TM, however, no integration with deep-rts yet. This would be very interesting, though.
One of our main activities right now is building an AI for the board game Hex, based on Monte Carlo Tree Search using the TM to evaluate board positions.
Will publish code here as we proceed:
https://github.com/cair/hex-ai
Integrating with Gym env is definitively on the TODO list.

**Comment by zdx3578** [comment]
@olegranmo  thanks very much! let me see this;

**Comment by zdx3578** [comment]
@olegranmo  now i am see  https://github.com/cair/pyTsetlinMachine/blob/master/pyTsetlinMachine/Tools.c file;but in paper no number_of_ta_chunks number_of_clause_chunks; now id dont know the mnist data is how to into the encodex;

**Comment by olegranmo** [comment]
The chunks are there because both the TA states and input are represented as bits, so there are e.g. 32 features in one 32-bit int. I guess it is best to use the Python-wrapper, with MNISTDemo.py as an example.
Note that I have just released 0.4.0, making classification 6 times faster and learning 3 times faster for MNIST.

**Comment by zdx3578** [comment]
@olegranmo thanks very much !

**Comment by zdx3578** [comment]
@olegranmo 现在conv operate is  one bit step ？ may be conv stride can increase？so number_of_patches  
 can  rapid descend；so less compute.

**Comment by olegranmo** [comment]
Good point, one-bit steps, so increasing stride would absolutely reduce cost. Have put it on the roadmap. Thanks!

**Comment by perara** [comment]
Hi,
I'm closing this. If there is any future questions regard DeepRTS, feel free to open a new issue :)
Best Regards
Per-Arne
