### ISSUE TITLE
pip3 install fails with pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by marcocspc** [cair/deep-rts#9]
The error is:

pkg_resources.DistributionNotFound: The 'DeepRTS' distribution was not found and is required by the application

Does this means that I need to have an older version installed before I can install release 2.5.0?

I'm trying to install this on MacOS. Tried on an Ubuntu container, but got the same error. I've made a dockerfile (attached) that works to build it, but it is a really old commit (based on help to issue #5), so I can't use it.

If I try to build this (on Ubuntu or Mac OS) from the latest commit, I get a lot of warnings and pip fails to install it.

Could you describe the correct way to install this? Thanks. 

[Dockerfile.txt](https://github.com/cair/deep-rts/files/3883204/Dockerfile.txt)

**Comment by perara** [comment]
Hi, ill see if i can get my hands on a ios machine to test this out.
Several people have issues on mac

**Comment by marcocspc** [comment]
Here's an output when trying to build in an Ubuntu container.

On this container I was able to install version 2.0.1. Then I could get over "pkg_resources.DistributionNotFound" error described above. But while compiling I get a lot of warnings and the installation fails.

I haven't tested this approach (installing version 2.0.1 before trying latest from github) on MacOS yet. But at least with an Ubuntu container, compilation is easier to reproduce.

You will see that at first I tried to install 2.5.0, but I couldn't do "git submodule update --init --recursive" inside its directory, so I went for latest from github.

I was on Ubuntu 18.04.

[Terminal Saved Output.txt](https://github.com/cair/deep-rts/files/3883856/Terminal.Saved.Output.txt)

**Comment by perara** [comment]
Hi,

Ill take a look at this in the morning and get back to you.

**Comment by perara** [comment]
> Here's an output when trying to build in an Ubuntu container.
> 
> On this container I was able to install version 2.0.1. Then I could get over "pkg_resources.DistributionNotFound" error described above. But while compiling I get a lot of warnings and the installation fails.
> 
> I haven't tested this approach (installing version 2.0.1 before trying latest from github) on MacOS yet. But at least with an Ubuntu container, compilation is easier to reproduce.
> 
> You will see that at first I tried to install 2.5.0, but I couldn't do "git submodule update --init --recursive" inside its directory, so I went for latest from github.
> 
> I was on Ubuntu 18.04.
> 
> [Terminal Saved Output.txt](https://github.com/cair/deep-rts/files/3883856/Terminal.Saved.Output.txt)

Hi again,
I've pushed a working docker sample onto the master branch
```FROM ubuntu:18.04
MAINTAINER Per-Arne Andersen

RUN apt-get update && apt-get install -y apt-utils python3 python3-pip git xvfb build-essential cmake

RUN git clone https://github.com/UIA-CAIR/DeepRTS.git drts --recurse-submodules
RUN pip3 install -e drts

RUN cat drts/coding/requirements.txt | xargs -n 1 pip3 install; exit 0
RUN cat drts/requirements.txt | xargs -n 1 pip3 install; exit 0

RUN Xvfb :99 -ac &

ENV SDL_VIDEODRIVER dummy

RUN python3 drts/coding/main.py```

I recommend to run with the master branch.
I have not yet gotten to test MacOS

**Comment by marcocspc** [comment]
Hello!

Thank you for your support.

One last question: if I remove the line "ENV SDL_VIDEODRIVER dummy", will the game run with a gui? (I will forward my X session to the container)

**Comment by perara** [comment]
Hi,
No problem, be sure to cite if you use it in your work! :)

Yes, the SDL_VIDEODRIVER dummy is simply so that SDL (the Graphics renderer) can run in non-x environments. As long as you have a running X instance (or other forms of GUI on other OSes) itis not required. I use it as it simply enables to run without gui, while still being able to extract rendered graphics for the game state :)
